### ISSUE TITLE
Doesn't share history with plinss/apiclient

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-apiclient#1]
@plinss has an outdated copy of apiclient at [plinss/apiclient](https://github.com/plinss/apiclient). This repo doesn't share its history with that one. It should, even though that means rewriting history (because we don't expect anyone to fork this any time soon!).

As I understood it, @plinss's repo was created with hg-git, as was this, hence one would expect them to share history. I couldn't manage to get hg-git to create a repo with those commits and the new ones.

**Comment by gsnedders** [comment]
(OTOH, the other repo has no forks, hence it's probably not the end of the world if this doesn't get resolved and they have totally disjoint histories.)

**Comment by plinss** [comment]
plinss/apiclient was probably made with a significantly older version of hg-git, which is why the histories won't match (it's also possible that hg-git was updated during the repo's lifetime which makes it very difficult to match up).

I updated my github mirror of apiclient if you want to sync to it

**Comment by gsnedders** [comment]
Annoying I couldn't mangle hg-git to do what I wanted it to (will try again at some point, I guess…), but it's now consistent with your mirror. Yay!
